(defpackage #:lisp-mcp-server/tests
  (:use #:cl)
  (:import-from #:rove)
  (:import-from #:lisp-mcp-server/tests/bridge-test)
  (:import-from #:lisp-mcp-server/tests/code-test)
  (:import-from #:lisp-mcp-server/tests/core-test)
  (:import-from #:lisp-mcp-server/tests/fs-test)
  (:import-from #:lisp-mcp-server/tests/logging-test)
  (:import-from #:lisp-mcp-server/tests/protocol-test)
  (:import-from #:lisp-mcp-server/tests/repl-test)
  (:import-from #:lisp-mcp-server/tests/lisp-read-file-test)
  (:import-from #:lisp-mcp-server/tests/validate-test)
  (:import-from #:lisp-mcp-server/tests/tcp-test)
  (:import-from #:lisp-mcp-server/tests/tools-test)
  (:import-from #:lisp-mcp-server/tests/integration-test))
(in-package #:lisp-mcp-server/tests)

(defmethod asdf:perform :after ((op asdf:test-op) (system (eql (asdf:find-system :lisp-mcp-server/tests))))
  (rove:run system))
